modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"


[[mods]]
modId = "littlemaid"
version = "${version}"
displayName = "LittleMaidRemade"
displayURL = "https://akazukin.org"
logoFile = "little_maid.png"
ordering = "NONE"
side = "BOTH"

authors = "Akazukin-Team"
description = '''A mod that was remade the mod 'Little Maid Mod' by Akazukin-Team'''


[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"


# Here's another dependency
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "=1.21.5"
ordering = "NONE"
side = "BOTH"
